import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/useable/navbar";
import { Source_Serif_4 } from "next/font/google";
import { Inter } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "../../components/useable/footer";
import Navbar2 from "../../components/useable/navbar2";
import "swiper/css";
import AuthProvider from "../../components/useable/AuthProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
  weight: ["400", "600", "700"], // adjust as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sourceSerif.variable} ${inter.variable} antialiased  overflow-x-hidden`}
      >
        {/* <Navbar /> */}
        <AuthProvider>
          <Navbar2 />
        <div className="h-20" />
        {children}
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
